:Author: dimcoord
:Email: dimastio20062@gmail.com
:Date: 24/12/2022
:Revision: version#
:License: Public Domain

= Geodata Acquisition and Utilization Semi-system

GAUSS (Geodata Acquisition and Utilization Semi-system) is yet another soil moisture monitoring tool. It's fully-strapped tool with some thingamajig to improve the usability of this kind of tool. We're trying to solve the problem of sudden dryness in certain areas such as Indonesia. To monitor and pinpoint which areas have the least moisture, and locate those with the most accesible way possible.

We added spatial pinpointing by using a GPS module, deployed a web application, and integrated the whole system into the webapp as well as adding an interactive map.

Devpost: https://devpost.com/software/gauss-for-the-environment

=== Preparations
Add the bill of the materials you need for this project.

|===
| ID | Part name      | Quantity
| 01 | WeMos D1 R32   | 1
| 02 | HW-103         | 1
| 03 | HW-080         | 1
| 04 | UBLOX NEO-6M   | 1
| 05 | AA Batteries   | 6
| 06 | 6S AA Holder w/ 3.5mm Jack  | 1
| 07 | Breadboard     | 1
| 08 | Mini Breadboard | 1
| 09 | Jumper cables  | 25
| 10 | Push button    | 1
| 11 | 1k Resistor    | 1
|===

== Step 1: Installation
To install the project, first you must do these things:

1. Clone or download this project to your computer.
2. Extract and put the whole thing into a folder.
3. Open the soil_moisture_sensor.ino in Arduino IDE.

== Step 2: Assemble the circuit

Assemble the circuit following the diagram layout.png attached to the sketch.

== Step 3: Load the code

1. In Arduino IDE, install ESP32 boards from the Boards Manager.
2. Connect your board into the computer.
3. Upload the code contained in this sketch on to your board.

=== Folder structure

....
 (create folder)              => Arduino sketch folder
  ├── soil_moisture_sensor.ino       => main Arduino file
  ├── schematics.png          => (optional) an image of the required schematics
  ├── layout.png              => (optional) an image of the layout
  └── ReadMe.adoc             => this file
....

=== License
This project is released under a Public Domain License.

=== Contributing
To contribute to this project please contact dutchieslierk https://id.arduino.cc/dutchieslierk

=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents.
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
